pipeline {
    agent { label 'AGENT' }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Select action'
        )
    }

    stages {

        stage('Init') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh '''
                        cd 00-vpc
                        terraform init -reconfigure
                    '''
                }
            }
        }

        stage('Destroy') {
            when {
                expression { params.ACTION == 'destroy' }
            }

            input {
                message 'Are you sure you want to destroy the VPC?'
                ok 'Destroy'
            }

            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh '''
                        cd 00-vpc
                        terraform destroy -auto-approve
                    '''
                }
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}